# Example input.yaml for EWC with computed Fisher information
# '*' signifies default. You can check log.sevenn for defaults.

model:  # model keys should be consistent except for train_* keys
    chemical_species: 'Auto'
    cutoff: 5.0
    channel: 128
    is_parity: False
    lmax: 2
    num_convolution_layer: 5
    irreps_manual:
        - "128x0e"
        - "128x0e+64x1e+32x2e"
        - "128x0e+64x1e+32x2e"
        - "128x0e+64x1e+32x2e"
        - "128x0e+64x1e+32x2e"
        - "128x0e"

    weight_nn_hidden_neurons: [64, 64]
    radial_basis:
        radial_basis_name: 'bessel'
        bessel_basis_num: 8
    cutoff_function:
        cutoff_function_name: 'XPLOR'
        cutoff_on: 4.5
    self_connection_type: 'linear'

    train_shift_scale: False   # customizable (True | False)
    train_denominator: False   # customizable (True | False)

train:  # Customizable
    random_seed: 1
    is_train_stress: True
    epoch: 100

    optimizer: 'adam'
    optim_param:
        lr: 0.004
    scheduler: 'exponentiallr'
    scheduler_param:
        gamma: 0.99

    force_loss_weight: 0.1
    stress_loss_weight: 1e-06

    per_epoch: 10  # Generate checkpoints every this epoch

    # ['target y', 'metric']
    # Target y: TotalEnergy, Energy, Force, Stress, Stress_GPa, TotalLoss
    # Metric  : RMSE, MAE, or Loss
    error_record:
        - ['Energy', 'RMSE']
        - ['Force', 'RMSE']
        - ['Stress', 'RMSE']
        - ['TotalLoss', 'None']
        - ['EWCLoss', 'None']  # Record EWC loss

    continue:
        reset_optimizer: True
        reset_scheduler: True
        reset_epoch: True
        checkpoint: 'SevenNet-0_11July2024'
        # Set True to use shift, scale, and avg_num_neigh from checkpoint (highly recommended)
        use_statistic_values_of_checkpoint: True
        calc_fisher: False
        loss_threshold: -1  # will be ignored
        opt_params: './opt_params_sevenn.pt'  # path to opt_params generated by calc_fisher
        fisher_information: './fisher_sevenn.pt'  # path to fisher_sevenn generated by calc_fisher
        ewc_lambda: 1e12  # EWC loss weight, will be divided by 2

data:  # Customizable
    batch_size: 4
    data_divide_ratio: 0.1

    data_format: 'ase'
    data_format_args:
        index: ':'

    load_dataset_path: ['fine_tune.extxyz']  # Support multiple files and expansion(*)
